### PR TITLE
rebuild for py311

### PR DESCRIPTION
**Pull request by boldorider4**
pytorch-lightning 1.9.5 rebuild for py311

**Destination channel:** defaults

### Links

- [PKG-5034]
- [Upstream repository](https://github.com/Lightning-AI/pytorch-lightning/tree/1.9.5)

[PKG-5034]: https://anaconda.atlassian.net/browse/PKG-5034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by danpetry — COMMENTED** [review]
Do you want to build neuralprophet for py 3.12? If so, it'd be better to build torchmetrics

**Comment by lorepirri** [comment]
> Do you want to build neuralprophet for py 3.12? If so, it'd be better to build torchmetrics

Strange that in `torchmetrics` there is no skip for `linux-64`, but the artifacts are not there. Maybe it would be enough to trigger a re-build.

https://github.com/AnacondaRecipes/torchmetrics-feedstock/pull/8/files

**Comment by lorepirri** [comment]
@boldorider4 please wait for https://github.com/AnacondaRecipes/torchmetrics-feedstock/pull/9

**Comment by danpetry** [comment]
> Strange that in torchmetrics there is no skip for linux-64, but the artifacts are not there. Maybe it would be enough to trigger a re-build.

Maybe we weren't building for python 3.12 at that point?

**Comment by lorepirri** [comment]
> > Strange that in torchmetrics there is no skip for linux-64, but the artifacts are not there. Maybe it would be enough to trigger a re-build.
> 
> Maybe we weren't building for python 3.12 at that point?

All the `py312` are there, except for `linux-64`, but there is no skip `py312` for `linux-64`.

```
for p in linux-{64,s390x,aarch64} win-64 osx-{64,arm64}; do echo -e "*** $p"; conda search -q --platform=$p "torchmetrics==1.1.2" -c main --override-channels; echo ""; done
*** linux-64
Loading channels: ...working... done
# Name                       Version           Build  Channel
torchmetrics                   1.1.2 py310h06a4308_0  main
torchmetrics                   1.1.2 py311h06a4308_0  main
torchmetrics                   1.1.2  py38h06a4308_0  main
torchmetrics                   1.1.2  py39h06a4308_0  main

*** linux-s390x
Loading channels: ...working... done
# Name                       Version           Build  Channel
torchmetrics                   1.1.2 py310ha847dfd_0  main
torchmetrics                   1.1.2 py311ha847dfd_0  main
torchmetrics                   1.1.2 py312ha847dfd_0  main
torchmetrics                   1.1.2  py38ha847dfd_0  main
torchmetrics                   1.1.2  py39ha847dfd_0  main

*** linux-aarch64
Loading channels: ...working... done
# Name                       Version           Build  Channel
torchmetrics                   1.1.2 py310hd43f75c_0  main
torchmetrics                   1.1.2 py311hd43f75c_0  main
torchmetrics                   1.1.2 py312hd43f75c_0  main
torchmetrics                   1.1.2  py38hd43f75c_0  main
torchmetrics                   1.1.2  py39hd43f75c_0  main

*** win-64
Loading channels: ...working... done
# Name                       Version           Build  Channel
torchmetrics                   1.1.2 py310haa95532_0  main
torchmetrics                   1.1.2 py311haa95532_0  main
torchmetrics                   1.1.2 py312haa95532_0  main
torchmetrics                   1.1.2  py38haa95532_0  main
torchmetrics                   1.1.2  py39haa95532_0  main

*** osx-64
Loading channels: ...working... done
# Name                       Version           Build  Channel
torchmetrics                   1.1.2 py310hecd8cb5_0  main
torchmetrics                   1.1.2 py311hecd8cb5_0  main
torchmetrics                   1.1.2 py312hecd8cb5_0  main
torchmetrics                   1.1.2  py38hecd8cb5_0  main
torchmetrics                   1.1.2  py39hecd8cb5_0  main

*** osx-arm64
Loading channels: ...working... done
# Name                       Version           Build  Channel
torchmetrics                   1.1.2 py310hca03da5_0  main
torchmetrics                   1.1.2 py311hca03da5_0  main
torchmetrics                   1.1.2 py312hca03da5_0  main
torchmetrics                   1.1.2  py38hca03da5_0  main
torchmetrics                   1.1.2  py39hca03da5_0  main

```

**Comment by danpetry** [comment]
oh I see.

**Review by cbouss — APPROVED** [review]

**Review by lorepirri — APPROVED** [review]

**Comment by lorepirri** [comment]
@boldorider4 `torchmetrics 1.1.2` is done, you can remove the staging channel.

**Review by skupr-anaconda — APPROVED** [review]

**Review by danpetry — APPROVED** [review]

**Pull request merged**
